name: user-cd-main

on:
  push:
    branches: [ main ]
jobs:
  ci:
    uses: fga-eps-mds/2023-1-schedula-gestor-de-usuarios/.github/workflows/user-ci.yml@main

  deploy:
    needs: [ ci ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY_PRD}}
        heroku_app_name: ${{secrets.HEROKU_APP_NAME_PRD}}
        heroku_email: ${{secrets.HEROKU_EMAIL_PRD}}
        branch: main